# Generated by Django 5.2.14 on 2026-05-29 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_question_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.IntegerField(verbose_name='總題數')),
                ('correct_count', models.IntegerField(verbose_name='答對題數')),
                ('score_percent', models.IntegerField(verbose_name='得分率')),
                ('duration', models.CharField(max_length=10, verbose_name='花費時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作答時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
