# Generated by Django 5.2.14 on 2026-05-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quizrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, default='暫無解析。', null=True, verbose_name='題目解析'),
        ),
    ]
